# Generated by Django 5.0.3 on 2024-03-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(db_default=0),
        ),
    ]
