# Generated by Django 5.0.3 on 2024-03-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=models.CharField(max_length=50), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
