# Generated by Django 5.0.3 on 2024-04-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_remove_downloads_product_downloads_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='product',
        ),
        migrations.AlterField(
            model_name='downloads',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='product',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
