# Generated by Django 5.0.3 on 2024-04-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0006_remove_downloads_product_alter_downloads_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='product',
            field=models.CharField(default='', max_length=50),
        ),
    ]
